filter:
    paths: [ src/* ]
checks:
    php: true
tools:
    external_code_coverage:
        timeout: 600
build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
