language: php

php:
  - 8.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update

install: composer install --prefer-source

script: XDEBUG_MODE=coverage vendor-bin/dev/vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
