name: Run CI build script

on:
    workflow_call:
    pull_request:
        types: [ opened, reopened, edited, synchronize ]
        branches:
            - master
jobs:
    quality_control:
        name: Execute code quality checks
        runs-on: ubuntu-latest
        
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
                with:
                    ref: ${{ github.event.pull_request.head.sha }}
                    fetch-depth: 10

            -   name: Mark repository as safe
                run: git config --global --add safe.directory $GITHUB_WORKSPACE

            -   name: Setup python
                uses: actions/setup-python@v4
                id: setup-python
                with:
                    python-version: 3.12

            -   name: Run pipenv
                uses: tiagovrtr/actions-pipenv@v1
                with:
                    pipenv-version: v2023.12.1

            -   run: pipenv --python ${{ steps.setup-python.outputs.python-path }}

            -   name: Run tests and code quality checks
                run: |
                    pipenv install
                    pipenv run python bin/ci.py --verbose --teardown
                env:
                    COMPOSER_ROOT_VERSION: ${{ vars.COMPOSER_ROOT_VERSION }}

            -   name: Upload Scrutinizer coverage
                uses: sudo-bot/action-scrutinizer@latest
                # Do not run this step on forked versions of the main repository (example: contributor forks)
                if: github.repository == 'runopencode/query-resources-loader-bundle'
                with:
                    cli-args: "--format=php-clover build/phpunit/clover.xml --revision=${{ github.event.pull_request.head.sha || github.sha }}"                    

