name: Release

on:
    push:
        branches:
            - master

permissions:
    contents: read

jobs:
#    ci:
#        uses: ./.github/workflows/ci.yaml
    release:
        name: Release
        runs-on: ubuntu-latest
        permissions:
            contents: write
            issues: write
            pull-requests: write
#        needs:
#            - ci

        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0
                    
            -   name: Mark repository as safe
                run: git config --global --add safe.directory $GITHUB_WORKSPACE                    
                    
            -   name: Setup Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: "lts/*"
            -   name: Install dependencies
                run: npm clean-install
            -   name: Release
                env:
                    GH_TOKEN: ${{ secrets.GH_TOKEN }}
                run: npx semantic-release                
                